// Model Barrel File — Re-exports all Mongoose models
// Import from here: const { User, Brand } = require('./models');

module.exports = {
  User: require('./User'),
  InfluencerProfile: require('./InfluencerProfile'),
  BrandProfile: require('./BrandProfile'),
  Brand: require('./Brand'),
  BrandMember: require('./BrandMember'),
  Campaign: require('./Campaign'),
  Reward: require('./Reward'),
  ContentSubmission: require('./ContentSubmission'),
  Partnership: require('./Partnership'),
  GuestReviewer: require('./GuestReviewer'),
  KioskReward: require('./KioskReward'),
  Subscription: require('./Subscription'),
  Transaction: require('./Transaction'),
  Payout: require('./Payout'),
  Withdrawal: require('./Withdrawal'),
  Notification: require('./Notification'),
  ClaimRequest: require('./ClaimRequest'),
  BrandScan: require('./BrandScan'),
  BrandInvite: require('./BrandInvite'),
  PurchasePointsConfig: require('./PurchasePointsConfig'),
  PurchasePointsLog: require('./PurchasePointsLog'),
  GoogleBusinessConfig: require('./GoogleBusinessConfig'),
  ContentReport: require('./ContentReport'),
  UserBlock: require('./UserBlock'),
  BrandMusic: require('./BrandMusic'),
  BrandCatalog: require('./BrandCatalog'),
  Promotion: require('./Promotion'),
};
